index:
   path: /
   controller: App\Controller\FrontController::index

login:
   path: /login
   controller: App\Controller\Pages\LoginController::index

back:
   path: /backoffice
   controller: App\Controller\BackController::index